logs/urls.py
# Re2o est un logiciel d'administration développé initiallement au rezometz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Goulven Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^stats_logs$', views.stats_logs, name='stats-logs'),
    url(r'^revert_action/(?P<revision_id>[0-9]+)$', views.revert_action, name='revert-action'),
    url(r'^stats_general/$', views.stats_general, name='stats-general'),
    url(r'^stats_models/$', views.stats_models, name='stats-models'),
    url(r'^stats_users/$', views.stats_users, name='stats-users'),
    url(r'^stats_actions/$', views.stats_actions, name='stats-actions'),
]

machines/urls.py
# Re2o est un logiciel d'administration développé initiallement au rezometz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Goulven Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new_machine/(?P<userid>[0-9]+)$', views.new_machine, name='new-machine'),
    url(r'^edit_interface/(?P<interfaceid>[0-9]+)$', views.edit_interface, name='edit-interface'),
    url(r'^del_machine/(?P<machineid>[0-9]+)$', views.del_machine, name='del-machine'),
    url(r'^new_interface/(?P<machineid>[0-9]+)$', views.new_interface, name='new-interface'),
    url(r'^del_interface/(?P<interfaceid>[0-9]+)$', views.del_interface, name='del-interface'),
    url(r'^add_machinetype/$', views.add_machinetype, name='add-machinetype'),
    url(r'^edit_machinetype/(?P<machinetypeid>[0-9]+)$', views.edit_machinetype, name='edit-machinetype'),
    url(r'^del_machinetype/$', views.del_machinetype, name='del-machinetype'),
    url(r'^index_machinetype/$', views.index_machinetype, name='index-machinetype'),
    url(r'^add_iptype/$', views.add_iptype, name='add-iptype'),
    url(r'^edit_iptype/(?P<iptypeid>[0-9]+)$', views.edit_iptype, name='edit-iptype'),
    url(r'^del_iptype/$', views.del_iptype, name='del-iptype'),
    url(r'^index_iptype/$', views.index_iptype, name='index-iptype'),
    url(r'^add_extension/$', views.add_extension, name='add-extension'),
    url(r'^edit_extension/(?P<extensionid>[0-9]+)$', views.edit_extension, name='edit-extension'),
    url(r'^del_extension/$', views.del_extension, name='del-extension'),
    url(r'^add_mx/$', views.add_mx, name='add-mx'),
    url(r'^edit_mx/(?P<mxid>[0-9]+)$', views.edit_mx, name='edit-mx'),
    url(r'^del_mx/$', views.del_mx, name='del-mx'),
    url(r'^add_text/$', views.add_text, name='add-text'),
    url(r'^edit_text/(?P<textid>[0-9]+)$', views.edit_text, name='edit-text'),
    url(r'^del_text/$', views.del_text, name='del-text'),
    url(r'^add_ns/$', views.add_ns, name='add-ns'),
    url(r'^edit_ns/(?P<nsid>[0-9]+)$', views.edit_ns, name='edit-ns'),
    url(r'^del_ns/$', views.del_ns, name='del-ns'),
    url(r'^index_extension/$', views.index_extension, name='index-extension'),
    url(r'^add_alias/(?P<interfaceid>[0-9]+)$', views.add_alias, name='add-alias'),
    url(r'^edit_alias/(?P<aliasid>[0-9]+)$', views.edit_alias, name='edit-alias'),
    url(r'^del_alias/(?P<interfaceid>[0-9]+)$', views.del_alias, name='del-alias'),
    url(r'^index_alias/(?P<interfaceid>[0-9]+)$', views.index_alias, name='index-alias'),
    url(r'^add_service/$', views.add_service, name='add-service'),
    url(r'^edit_service/(?P<serviceid>[0-9]+)$', views.edit_service, name='edit-service'),
    url(r'^del_service/$', views.del_service, name='del-service'),
    url(r'^index_service/$', views.index_service, name='index-service'),
    url(r'^add_vlan/$', views.add_vlan, name='add-vlan'),
    url(r'^edit_vlan/(?P<vlanid>[0-9]+)$', views.edit_vlan, name='edit-vlan'),
    url(r'^del_vlan/$', views.del_vlan, name='del-vlan'),
    url(r'^index_vlan/$', views.index_vlan, name='index-vlan'),
    url(r'^add_nas/$', views.add_nas, name='add-nas'),
    url(r'^edit_nas/(?P<nasid>[0-9]+)$', views.edit_nas, name='edit-nas'),
    url(r'^del_nas/$', views.del_nas, name='del-nas'),
    url(r'^index_nas/$', views.index_nas, name='index-nas'),
    url(r'^history/(?P<object>machine)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>interface)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>machinetype)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>extension)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>mx)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>ns)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>text)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>iptype)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>alias)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>vlan)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>nas)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>service)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^$', views.index, name='index'),
    url(r'^rest/mac-ip/$', views.mac_ip, name='mac-ip'),
    url(r'^rest/regen-achieved/$', views.regen_achieved, name='regen-achieved'),
    url(r'^rest/mac-ip-dns/$', views.mac_ip_dns, name='mac-ip-dns'),
    url(r'^rest/alias/$', views.alias, name='alias'),
    url(r'^rest/corresp/$', views.corresp, name='corresp'),
    url(r'^rest/mx/$', views.mx, name='mx'),
    url(r'^rest/ns/$', views.ns, name='ns'),
    url(r'^rest/text/$', views.text, name='text'),
    url(r'^rest/zones/$', views.zones, name='zones'),
    url(r'^rest/service_servers/$', views.service_servers, name='service-servers'),
    ]

re2o/urls.py
# Re2o est un logiciel d'administration développé initiallement au rezometz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Goulven Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""re2o URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import index

urlpatterns = [
    url(r'^$', index),
    url('^logout/', auth_views.logout, {'next_page': '/'}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^cotisations/', include('cotisations.urls', namespace='cotisations')),
    url(r'^machines/', include('machines.urls', namespace='machines')),
    url(r'^topologie/', include('topologie.urls', namespace='topologie')),
    url(r'^logs/', include('logs.urls', namespace='logs')),
    url(r'^preferences/', include('preferences.urls', namespace='preferences')),

]

users/urls.py
# Re2o est un logiciel d'administration développé initiallement au rezometz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Goulven Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new_user/$', views.new_user, name='new-user'),
    url(r'^edit_info/(?P<userid>[0-9]+)$', views.edit_info, name='edit-info'),
    url(r'^state/(?P<userid>[0-9]+)$', views.state, name='state'),
    url(r'^password/(?P<userid>[0-9]+)$', views.password, name='password'),
    url(r'^new_serviceuser/$', views.new_serviceuser, name='new-serviceuser'),
    url(r'^edit_serviceuser/(?P<userid>[0-9]+)$', views.edit_serviceuser, name='edit-serviceuser'),
    url(r'^del_serviceuser/(?P<userid>[0-9]+)$', views.del_serviceuser, name='del-serviceuser'),
    url(r'^add_ban/(?P<userid>[0-9]+)$', views.add_ban, name='add-ban'),
    url(r'^edit_ban/(?P<banid>[0-9]+)$', views.edit_ban, name='edit-ban'),
    url(r'^add_whitelist/(?P<userid>[0-9]+)$', views.add_whitelist, name='add-whitelist'),
    url(r'^edit_whitelist/(?P<whitelistid>[0-9]+)$', views.edit_whitelist, name='edit-whitelist'),
    url(r'^add_right/(?P<userid>[0-9]+)$', views.add_right, name='add-right'),
    url(r'^del_right/$', views.del_right, name='del-right'),
    url(r'^add_school/$', views.add_school, name='add-school'),
    url(r'^edit_school/(?P<schoolid>[0-9]+)$', views.edit_school, name='edit-school'),
    url(r'^del_school/$', views.del_school, name='del-school'),
    url(r'^add_listright/$', views.add_listright, name='add-listright'),
    url(r'^edit_listright/(?P<listrightid>[0-9]+)$', views.edit_listright, name='edit-listright'),
    url(r'^del_listright/$', views.del_listright, name='del-listright'),
    url(r'^profil/(?P<userid>[0-9]+)$', views.profil, name='profil'),
    url(r'^index_ban/$', views.index_ban, name='index-ban'),
    url(r'^index_white/$', views.index_white, name='index-white'),
    url(r'^index_school/$', views.index_school, name='index-school'),
    url(r'^index_listright/$', views.index_listright, name='index-listright'),
    url(r'^index_serviceusers/$', views.index_serviceusers, name='index-serviceusers'),
    url(r'^mon_profil/$', views.mon_profil, name='mon-profil'),
    url(r'^process/(?P<token>[a-z0-9]{32})/$', views.process, name='process'),
    url(r'^reset_password/$', views.reset_password, name='reset-password'),
    url(r'^mass_archive/$', views.mass_archive, name='mass-archive'),
    url(r'^history/(?P<object>user)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>ban)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>whitelist)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>school)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>listright)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^history/(?P<object>serviceuser)/(?P<id>[0-9]+)$', views.history, name='history'),
    url(r'^$', views.index, name='index'),
    url(r'^rest/mailing/$', views.mailing, name='mailing'),

]

machines/templates/machines/aff_alias.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au rezometz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Goulven Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Alias</th>
                <th></th>
            </tr>
        </thead>
        {% for alias in alias_list %}
        <tr>
            <td>{{ alias }}</td>
            <td class="text-right">
		    {% include 'buttons/edit.html' with href='machines:edit-alias' id=alias.id %}
		    {% include 'buttons/history.html' with href='machines:history' name='alias' id=alias.id %}
            </td>
        </tr>
        {% endfor %}
    </table>

machines/templates/machines/aff_machines.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au rezometz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Goulven Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% if machines_list.paginator %}
{% include "pagination.html" with list=machines_list %}
{% endif %}

<table class="table">
    <thead>
        <tr>
            <th>Actions</th>
            <th>Proprietaire</th>
            <th>Nom dns</th>
            <th>Type</th>
            <th>Mac</th>
            <th>Ipv4</th>
            <th></th>
        </tr>
    </thead>
    {% for machine in machines_list %}
        {% for interface in machine.interface_set.all %}
        <tr class="active">
            {% if forloop.first %}
            <td rowspan="{{ machine.interface_set.all|length }}">
                {% include 'buttons/add.html' with href='machines:new-interface' id=machine.id desc='Ajouter une interface' %}
                {% include 'buttons/suppr.html' with href='machines:del-machine' id=machine.id %}
                {% include 'buttons/history.html' with href='machines:history' name='machine' id=machine.id %}
            </td>
            <td rowspan="{{ machine.interface_set.all|length }}">
                <a href="{% url 'users:profil' userid=machine.user.id %}"><b>{{ machine.user }}</b></a>
            </td>
            {% endif %}
            <td>
            {% if interface.domain.related_domain.all %}
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="editioninterface" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{ interface.domain }} <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="editioninterface">
                    {% for al in interface.domain.related_domain.all %}
                        <li>
                            <a href="http://{{ al }}">
                                {{ al }}
                                <i class="glyphicon glyphicon-share-alt"></i>
                            </a>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            {% else %}
                {{ interface.domain }}
            {% endif %}
            </td>
            <td>{{ interface.type }}</td>
            <td>{{ interface.mac_address }}</td>
            <td>{{ interface.ipv4 }}</td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="editioninterface" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Modifier <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="editioninterface">
                        <li>
                            <a href="{% url 'machines:edit-interface' interface.id %}">
                                <i class="glyphicon glyphicon-edit"></i> Editer
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'machines:index-alias' interface.id %}">
                                <i class="glyphicon glyphicon-edit"></i> Gerer les alias
                            </a>
                        </li>
			<li>
                            <a href="{% url 'machines:history' 'interface' interface.id %}">
                                <i class="glyphicon glyphicon-time"></i> Historique
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'machines:del-interface' interface.id %}">
                                <i class="glyphicon glyphicon-trash"></i> Supprimer
                            </a>
                        </li>
                    </ul>
                </div>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="8"></td>
        </tr>
    {% endfor %}
</table>

machines/templates/machines/index_alias.html
{% extends "machines/sidebar.html" %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au rezometz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Goulven Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}

{% block title %}Machines{% endblock %}

{% block content %}
  <h2>Liste des alias de l'interface</h2>
  <a class="btn btn-primary btn-sm" role="button" href="{% url 'machines:add-alias' interface_id  %}"><i class="glyphicon glyphicon-plus"></i> Ajouter un alias</a>
  <a class="btn btn-danger btn-sm" role="button" href="{% url 'machines:del-alias'  interface_id %}"><i class="glyphicon glyphicon-trash"></i> Supprimer un ou plusieurs alias</a>
  {%  include "machines/aff_alias.html" with  alias_list=alias_list %}
  <br />
  <br />
  <br />
{% endblock %}

machines/templates/machines/index_machinetype.html
{% extends "machines/sidebar.html" %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au rezometz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Goulven Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}

{% block title %}Machines{% endblock %}

{% block content %}
  <h2>Liste des types de machines</h2>
  {% if is_infra %}
  <a class="btn btn-primary btn-sm" role="button" href="{% url 'machines:add-machinetype'  %}"><i class="glyphicon glyphicon-plus"></i> Ajouter un type de machine</a>
  <a class="btn btn-danger btn-sm" role="button" href="{% url 'machines:del-machinetype'  %}"><i class="glyphicon glyphicon-trash"></i> Supprimer un ou plusieurs types de machines</a>
  {% endif %}
  {%  include "machines/aff_machinetype.html" with  machinetype_list=machinetype_list %}
  <br />
  <br />
  <br />
{% endblock %}

machines/templates/machines/index_nas.html
{% extends "machines/sidebar.html" %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au rezometz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Goulven Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}

{% block title %}Machines{% endblock %}

{% block content %}
  <h2>Liste des nas</h2>
  <h5>La correpondance nas-machinetype relie le type de nas à un type de machine.
  Elle est utile pour l'autoenregistrement des macs par radius, et permet de choisir le type de machine à affecter aux machines en fonction du type de nas</h5>
  <a class="btn btn-primary btn-sm" role="button" href="{% url 'machines:add-nas' %}"><i class="glyphicon glyphicon-plus"></i> Ajouter un type de nas</a>
  <a class="btn btn-danger btn-sm" role="button" href="{% url 'machines:del-nas'  %}"><i class="glyphicon glyphicon-trash"></i> Supprimer un ou plusieurs types nas</a>
  {%  include "machines/aff_nas.html" with  nas_list=nas_list %}
  <br />
  <br />
  <br />
{% endblock %}

machines/templates/machines/sidebar.html
{% extends "base.html" %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au rezometz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Goulven Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}


{% block sidebar %}
    {% if is_cableur %}
    <a class="list-group-item list-group-item-info" href="{% url "machines:index" %}">
        <i class="glyphicon glyphicon-list"></i>
        Machines
    </a>
    <a class="list-group-item list-group-item-info" href="{% url "machines:index-machinetype" %}">
        <i class="glyphicon glyphicon-list"></i>
        Types de machines
    </a>
    <a class="list-group-item list-group-item-info" href="{% url "machines:index-extension" %}">
        <i class="glyphicon glyphicon-list"></i>
        Extensions et zones
    </a>
    <a class="list-group-item list-group-item-info" href="{% url "machines:index-iptype" %}">
        <i class="glyphicon glyphicon-list"></i>
        Plages d'IP
    </a>
    <a class="list-group-item list-group-item-info" href="{% url "machines:index-vlan" %}">
        <i class="glyphicon glyphicon-list"></i>
        Vlans
    </a>
    <a class="list-group-item list-group-item-info" href="{% url "machines:index-nas" %}">
        <i class="glyphicon glyphicon-list"></i>
        Gestion des nas
    </a>
    <a class="list-group-item list-group-item-info" href="{% url "machines:index-service" %}">
        <i class="glyphicon glyphicon-list"></i>
        Services (dhcp, dns...)
    </a>   
    {% endif %}
{% endblock %}